[package]
name = "xhuzzzz/tagforge"
description = "A strongly typed CollectionService component binder for Roblox."
version = "0.1.0"
license = "MIT"
authors = ["Xhuzzzz"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/Xhuzzzz/TagForge"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
